rules = [
  OrganizeImports,
  RemoveUnused,
  LeakingImplicitClassVal,
  NoValInForComprehension,
]

OrganizeImports {
  groups = ["re:javax?\\.", "scala.", "*"]
  removeUnused = true
  groupedImports = Merge
}